/**
 * Dataset-backed providers over the open data bundled in `public/data`
 * (generated by `npm run data:build`, see scripts/data/README.md):
 *
 *   scripture          13 versions (translations.ts): BSB (default), KJV, WEB; BLIVRE, NBV, BPM;
 *                      RVR1909, BLM, VBL; LSG, DARBY, NCL, OST — all in English versification
 *                                                          bible/{id lowercased}/{BOOK}.json
 *   originalText       STEPBible TAGNT / TAHOT             original/{BOOK}.json
 *   lexicon            STEPBible TBESG / TBESH + concordance  lexicon/…, concordance/…
 *   crossReferences    OpenBible.info votes                xrefs/{BOOK}.json
 *   commentary         Tyndale notes + Calvin, Henry, JFB, Keil & Delitzsch   commentary/{id}/{BOOK}.json
 *   historicalContext  Tyndale book introductions          intros/{BOOK}.json
 *
 * Everything is fetched lazily per book / shard; nothing from public/data is bundled into JS.
 */
import type { ProviderRegistryOptions } from '../registry';
import type { ProviderRegistry } from '../types';
import { LocalCommentaryProvider } from './commentary';
import { LocalCrossReferenceProvider } from './crossReferences';
import { LocalHistoricalContextProvider } from './historicalContext';
import { LocalLexiconProvider } from './lexicon';
import { cachedLoader, createFetchLoader, defaultDataBaseUrl } from './loader';
import { LocalOriginalTextProvider } from './originalText';
import { LocalScriptureProvider } from './scripture';
import type { LocalProviderOptions } from './types';

export type LocalDatasetProviders = Pick<
  ProviderRegistry,
  'scripture' | 'originalText' | 'lexicon' | 'crossReferences' | 'commentary' | 'historicalContext'
>;

/** Compose the local dataset providers. Pass `loader` to read the data some other way (tests use the file system). */
export function createLocalDatasetProviders(options: ProviderRegistryOptions | LocalProviderOptions = {}): LocalDatasetProviders {
  const opts = options as LocalProviderOptions;
  const loader = opts.loader ? cachedLoader(opts.loader) : createFetchLoader(opts.dataBaseUrl ?? defaultDataBaseUrl());
  const scripture = new LocalScriptureProvider(loader);
  return {
    scripture,
    originalText: new LocalOriginalTextProvider(loader),
    lexicon: new LocalLexiconProvider(loader),
    crossReferences: new LocalCrossReferenceProvider(loader),
    commentary: new LocalCommentaryProvider({
      loader,
      verseCount: (book, chapter) => scripture.getVerseCount(book, chapter),
      allowRemoteFallback: opts.allowRemoteFallback !== false,
      remoteFetch: opts.remoteFetch,
    }),
    historicalContext: new LocalHistoricalContextProvider(loader),
  };
}

export { LocalCommentaryProvider, LOCAL_COMMENTARIES } from './commentary';
export { LocalCrossReferenceProvider } from './crossReferences';
export { LocalHistoricalContextProvider } from './historicalContext';
export { LocalLexiconProvider } from './lexicon';
export { createFetchLoader, defaultDataBaseUrl, type DataLoader } from './loader';
export { describeGreekMorph, describeHebrewMorph, describeLexiconMorph, describeMorph } from './morphology';
export { LocalOriginalTextProvider } from './originalText';
export { LOCAL_TRANSLATIONS, LocalScriptureProvider } from './scripture';
export { normalizeStrong, strongBase, type NormalizedStrong } from './strong';
export type * from './types';
